version: "3.9"

services:
  vue-app:
    build: .
    container_name: frontend-sipanji
    restart: always

    networks:
      - app-network

    deploy:
      resources:
        limits:
          memory: 256M

networks:
  app-network:
    external: true